'use strict';

module.exports = {
  dependencies: [
    'axios',
    'immutable',
    'react',
    'react-dom',
    'react-redux',
    'redux',
    'redux-saga'
  ],
  devDependencies: [
    'babel-core',
    'babel-eslint',
    'babel-loader',
    'babel-polyfill',
    'babel-preset-latest',
    'babel-preset-react',
    'babel-preset-stage-1',
    'babel-plugin-syntax-flow',
    'babel-plugin-transform-flow-strip-types',
    'conventional-changelog-cli',
    'case-sensitive-paths-webpack-plugin',
    'css-loader',
    'enzyme',
    'eslint',
    'eslint-config-sky',
    'extract-text-webpack-plugin',
    'flow-bin',
    'flow-typed',
    'flow-status-webpack-plugin',
    'identity-obj-proxy',
    'jest',
    'jsdom',
    'react-addons-test-utils',
    'redux-devtools',
    'react-hot-loader@next',
    'style-loader',
    'stylelint',
    'stylelint-config-sky',
    'postcss-loader',
    'postcss-cssnext',
    'postcss-mixins',
    'postcss-reporter',
    'postcss-smart-import',
    'postcss-browser-reporter',
    'webpack',
    'webpack-dashboard',
    'webpack-dev-server',
    'webpack-merge'
  ]
};
