'use strict';

module.exports = {
  dependencies: [
    'react',
    'react-dom'
  ],
  devDependencies: [
    'autoprefixer',
    'ava',
    'babel-core',
    'babel-eslint',
    'babel-loader',
    'babel-polyfill',
    'babel-preset-latest',
    'babel-preset-react',
    'babel-preset-stage-1',
    'babel-plugin-syntax-flow',
    'babel-plugin-transform-flow-strip-types',
    'case-sensitive-paths-webpack-plugin',
    'conventional-changelog-cli',
    'css-loader',
    'enzyme',
    'eslint',
    'eslint-plugin-react',
    'eslint-config-sky',
    'extract-text-webpack-plugin@beta',
    'flow-bin',
    'flow-typed',
    'flow-status-webpack-plugin',
    'ignore-styles',
    'jsdom',
    'react-addons-test-utils',
    'react-hot-loader@3.0.0-beta.6',
    'sinon',
    'stylelint',
    'stylelint-config-sky',
    'style-loader',
    'postcss-loader',
    'postcss-cssnext',
    'postcss-mixins',
    'postcss-reporter',
    'postcss-smart-import',
    'postcss-browser-reporter',
    'webpack@beta',
    'webpack-dashboard',
    'webpack-dev-server@beta',
    'webpack-merge'
  ]
};
